from enum import Enum

class ModelType(Enum):
    IMAGECLASSIFICATION = "IMAGECLASSIFICATION"
    OBJECTDETECTION = "OBJECTDETECTION"
    NLPCLASSIFICATION = "NLPCLASSIFICATION"
    TIMESERIESPREDICTION = "TIMESERIESPREDICTION"